apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-configmap
data:
  default.conf: |
    upstream backend {
        server localhost:5000;
    }

    server {
        listen 80;

        server_name _;

        access_log  /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log debug;

        root /app/build/;

        location / {
            try_files $uri @backend;
        }

        location @backend {
            proxy_pass http://backend;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Deny access to htaccess and htpasswd files
        location ~ /\.ht {
            deny  all;
        }

        # Deny access to hidden files
        location ~ /\. {
            access_log off; log_not_found off; deny all;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connections
  labels:
    app: connections
spec:
  selector:
    matchLabels:
      app: connections
  template:
    metadata:
      labels:
        app: connections
    spec:
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: nginx-config-configmap
      containers:
        - name: connections
          image: connections-image
          env:
            - name: FLASK_APP
              value: connections.app
            - name: DB_HOST
              value: connections-mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: very_secure_password
            - name: DB_NAME
              value: connections_db
          ports:
            - containerPort: 5000
        - name: connections-nginx
          image: nginx:stable-alpine
          volumeMounts:
            - name: nginx-conf-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          ports:
            - containerPort: 80
