apiVersion: v1
kind: Service
metadata:
  name: connections-mysql
  labels:
    app: connections
spec:
  ports:
    - port: 3306
  selector:
    app: connections
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: connections
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connections-mysql
  labels:
    app: connections
spec:
  selector:
    matchLabels:
      app: connections
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: connections
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7.22
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: very_secure_password
        command: ["/bin/sh"]
        args: ["-c", "echo 'CREATE DATABASE IF NOT EXISTS connections_db; CREATE DATABASE IF NOT EXISTS connections_db_test;' > /docker-entrypoint-initdb.d/init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"]
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
